spring.application.name=job4u

#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/job_4u
spring.datasource.username=root
spring.datasource.password=toanhg1231
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
###

#config jwt
###
nguyentoan.jwt.base64-secret=CGPKuIaxBQ/k0ENjqpx7USTi9hCD5LQSVxMh61PfJok+c3OXuVhaeDTg75RQkFlv8AKC2Y3rK8/Q3EaafhWCCg==
#expiration: 1 day
nguyentoan.jwt.access-token-validity-in-seconds=86400
nguyentoan.jwt.refresh-token-validity-in-seconds=8640000
###

#config upload file
###
#default = 1MB
spring.servlet.multipart.max-file-size=50MB

#default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB

#base path
nguyentoan.upload-file.base-uri=file:///D:/Code/JAVA/upload/
###

###
#config pagination
#start page = 1
spring.data.web.pageable.one-indexed-parameters=true
###

###
#config email with Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyentoan3108hg@gmail.com
spring.mail.password=vshsyzbmcusyciky
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###

###
#config login google
spring.security.oauth2.client.registration.google.client-id=9005289396-3mmii96igm1lotc0gkpsi74rlf9e9f1c.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

###
